swagger: "2.0"
info:
  description: "This is an API for mutants DNA analysis."
  version: "1.0.0"
  title: "Mutants Analyser"
  contact:
    email: "aizaguirre@itba.edu.ar"

host: "mutants-analyser-api.herokuapp.com"
basePath: "/"

schemes:
  - "https"
paths:
  /mutant:
    post:
      tags:
        - "mutant"
      summary: "Analyses submitted DNA sequence and tells if it is mutant."
      description: ""
      operationId: "addAnalysis"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "overlapping"
          in: "query"
          description: "Boolean (true or false) indicating analyser to allow or ignore overlapping of chains in the same direction."
          required: false
          type: "boolean"
        - in: "body"
          name: "body"
          description: "DNA sequence to be analysed."
          required: true
          schema:
            $ref: "#/definitions/Mutant"
      responses:
        "200":
          description: "Mutant DNA."
        "403":
          description: "Human DNA."
        "400":
          description: "DNA already analysed or containing invalid characters."

  /stats:
    get:
      tags:
        - "stats"
      summary: "Get stats related to analysed humans and mutants quantity"
      description: "Returns the quantity of analysed humans, analysed mutants and the ratio of mutants."
      operationId: "getStats"
      produces:
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Stats"


definitions:
  Mutant:
    type: "object"
    properties:
      dna:
        type: "array"
        items:
          type: "string"
  Stats:
    type: "object"
    properties:
      count_mutant_dna:
        type: "integer"
        format: "int64"
      count_human_dna:
        type: "integer"
        format: "int64"
      ratio:
        type: "number"
        format: "float64"
